### ISSUE TITLE
Can't get the Windows GUI wallet application to launch and create wallet 

### ISSUE THREAD

**Issue by Benjvoo** [EquilibriaCC/Equilibria#79]
After downloading and extracting files from (https://github.com/EquilibriaCC/Equilibria/releases), the application file does not launch when double clicked. If anyone has encountered/resolved this problem please advise. Thanks

**Comment by anushuiac** [comment]
Give us more details. What's your OS?
Windows, Linux or mac

**Comment by Benjvoo** [comment]
I am using Windows 10 Home, thanks

**Comment by Benjvoo** [comment]
Windows 10 Home, thanks

    On Saturday, May 7, 2022, 08:18:32 PM GMT+7, anushuiac ***@***.***> wrote:  
 
 


Give us more details. What's your OS?
Windows, Linux or mac

**Comment by anushuiac** [comment]
If you have antivirus running, theres chance that some of your file get removed or quarantine by av.

If you get a specific error, post here, or to discord/tg for wallet support.

~~~~

I forward the troubleshooting post in tg for you.

HOW TO TROUBLESHOOT YOUR GUI WALLET 
 
- Back up your seed -  You should always have noted down the seed of the wallets that you might have. This is essential to access your funds at any time since the creation of the wallet, and a way to restore if needed. 
 
- Check your Antivirus - Most of the issues are related to antivirus, check if it is blocking it and create an exception on it if it is the case. If you are unsure, disable it for a minute while opening the wallet to ensure that this is not the root cause. 
 
- Firewall - Check that the firewall connection does not block the wallet, specially if you are going to run a local node. Same as with the antivirus, if you are not sure, disable it while testing the wallet to ensure that it is not the firewall. 
 
- Use only the latest wallet - Always use the most up-to-date version of the wallet, can be checked either on the website or in the link below 
https://github.com/EquilibriaCC/Equilibria/releases/tag/v10.2.0  
 
 
------------------------------------------- 
 
Once all the above is checked, your wallet could not work due to different reasons 
 
- Wallet is trying to connect to a remote node that is down - this is the most common cause, easily fixable if we remove the settings file and reopen the wallet. It will ask you again which type of wallet you want to set, ensure that you try to connect to a node that it is up and running - you can check this typing “!xeq remote nodes” on Telegram or discord 
 
 Settings file location 
 - Mac: path /Users/yourownuser/.equilibria/gui , file config.json 
The folder above is hidden, to show hidden folders use the shortcut command + shift + "." 
-  Windows: path C:\ProgramData\equilibria\gui , file config.json 
- Linux: TBC 
 
- Your system might not be supported - if they are not up-to-date and has a few years. Try to have it fully updated if possible. 
 
In case all the above fails, you can always use the wallet in local node mode, this takes quite some time to synchronize the first time as you will download and verify the whole blockchain, but it is also safer and more reliable moving forward as you act as your own node. 
 
If none of the suggested work, you can always drop a message here or in Discord

**Comment by Benjvoo** [comment]
Thanks so much, I disabled antivirus software, redownloaded wallet software. That solved problem. GUI windows wallet now up and running !!!
    On Sunday, May 8, 2022, 12:45:43 PM GMT+7, anushuiac ***@***.***> wrote:  
 
 


If you have antivirus running, theres chance that some of your file get removed or quarantine by av.

If you get a specific error, post here, or to discord/tg for wallet support.

I forward the troubleshooting post in tg for you.

HOW TO TROUBLESHOOT YOUR GUI WALLET 
 
- Back up your seed -  You should always have noted down the seed of the wallets that you might have. This is essential to access your funds at any time since the creation of the wallet, and a way to restore if needed. 
 
- Check your Antivirus - Most of the issues are related to antivirus, check if it is blocking it and create an exception on it if it is the case. If you are unsure, disable it for a minute while opening the wallet to ensure that this is not the root cause. 
 
- Firewall - Check that the firewall connection does not block the wallet, specially if you are going to run a local node. Same as with the antivirus, if you are not sure, disable it while testing the wallet to ensure that it is not the firewall. 
 
- Use only the latest wallet - Always use the most up-to-date version of the wallet, can be checked either on the website or in the link below 
https://github.com/EquilibriaCC/Equilibria/releases/tag/v10.2.0  
 
 
------------------------------------------- 
 
Once all the above is checked, your wallet could not work due to different reasons 
 
- Wallet is trying to connect to a remote node that is down - this is the most common cause, easily fixable if we remove the settings file and reopen the wallet. It will ask you again which type of wallet you want to set, ensure that you try to connect to a node that it is up and running - you can check this typing “!xeq remote nodes” on Telegram or discord 
 
 Settings file location 
 - Mac: path /Users/yourownuser/.equilibria/gui , file config.json 
The folder above is hidden, to show hidden folders use the shortcut command + shift + "." 
-  Windows: path C:\ProgramData\equilibria\gui , file config.json 
- Linux: TBC 
 
- Your system might not be supported - if they are not up-to-date and has a few years. Try to have it fully updated if possible. 
 
In case all the above fails, you can always use the wallet in local node mode, this takes quite some time to synchronize the first time as you will download and verify the whole blockchain, but it is also safer and more reliable moving forward as you act as your own node. 
 
If none of the suggested work, you can always drop a message here or in Discord
